### ISSUE TITLE
Criar token de bot para Discord

### ISSUE THREAD

**Issue by ArthurSchSilva-Schneider** [Amongus-Inc/ReignsIFSC#14]
Obrigatório:

 Criar [aplicação no Discord](https://discord.com/developers/applications).
 Associar perfil de bot a aplicação.
 Criar variável de ambiente com o token no Gitpod.
 Definir lista de acesso (ACL) para o bot ter suporte a texto (message intent) e voz.

Referência: [discord.py: Creating a Bot Account](https://discordpy.readthedocs.io/en/stable/discord.html).

**Comment by Pedro-HML** [comment]
Seguindo o passo a passo, adicionamos o bot ao servidor do projeto.
