### ISSUE TITLE
Brainstormar (Tutorial)

### ISSUE THREAD

**Issue by Pedro-HML** [Amongus-Inc/ReignsIFSC#4]
Definir as questões de introdução às mecânicas apresentadas no tutorial

**Comment by Vmp3** [comment]
Tutorial praticamente finalizado, vamos discutir essa terça 27/09 para podermos implementá-lo e focar em outras coisas

**Comment by Vmp3** [comment]
tutorial discutido e aprovado pelo conselho mestre
